# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import eventx.subcriptions.validators


class Migration(migrations.Migration):

    dependencies = [
        ('subcriptions', '0003_auto_20170616_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='cpf',
            field=models.CharField(max_length=11, validators=[eventx.subcriptions.validators.validate_cpf], verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone'),
        ),
    ]
